"""Integration tests for search workflow.

Tests: API → Search service → Embedder → Qdrant → Reranking

This integration test verifies the complete search pipeline:
1. Query embedding generation via embedder microservice
2. Vector search in Qdrant vector database
3. Keyword search in PostgreSQL with full-text search
4. Hybrid search combining vector + keyword with RRF fusion
5. Cross-encoder reranking for precision improvement
6. Result ordering by relevance score

The test requires running services (API, search, embedder, Qdrant, PostgreSQL)
and will be skipped if RUN_INTEGRATION_TESTS environment variable is not set.
"""
import asyncio
import os
from typing import AsyncGenerator

import httpx
import pytest

# Skip marker for integration tests
pytestmark = pytest.mark.skipif(
    not os.getenv("RUN_INTEGRATION_TESTS"),
    reason="Integration tests require running services (set RUN_INTEGRATION_TESTS=1)",
)


@pytest.fixture
async def api_client() -> AsyncGenerator[httpx.AsyncClient, None]:
    """Create async HTTP client for API service.

    Yields:
        AsyncClient configured with 60-second timeout for search operations
        (longer timeout to account for embedding + search + reranking).
    """
    async with httpx.AsyncClient(
        base_url=os.getenv("API_BASE_URL", "http://localhost:8000"),
        timeout=60.0,
    ) as client:
        yield client


@pytest.fixture
async def test_corpus(api_client: httpx.AsyncClient) -> AsyncGenerator[list[dict], None]:
    """Upload test documents and return their metadata.

    Creates a diverse test corpus covering different topics to test
    semantic search, keyword search, and hybrid fusion capabilities.

    The corpus includes:
    - semantic_search.txt: About semantic search and embeddings
    - keyword_search.txt: About keyword/lexical search
    - rag_systems.txt: About RAG and retrieval-augmented generation
    - hybrid_fusion.txt: About combining search methods with RRF
    - cross_encoder.txt: About reranking and precision improvement

    Yields:
        List of document metadata dicts with 'id', 'title', and 'content' keys.
    """
    documents = [
        (
            "semantic_search.txt",
            b"""Semantic Search and Vector Embeddings

Semantic search uses vector embeddings to understand the meaning and context of queries.
Unlike traditional keyword matching, semantic search can find documents that are conceptually
similar even when they don't share the same terms. This is achieved through dense vector
representations generated by neural language models like BERT and sentence transformers.

Vector embeddings are high-dimensional numerical representations where semantically similar
texts are positioned close together in the vector space. The embeddings capture semantic
relationships, synonyms, and contextual meaning that keyword search cannot detect.

Popular embedding models include all-MiniLM-L6-v2, BERT, and MPNet. These models are trained
on large text corpora to learn semantic representations that work across many domains.
""",
            "Semantic Search Guide",
        ),
        (
            "keyword_search.txt",
            b"""Keyword Search and BM25 Ranking

Keyword search, also known as lexical search or term-based search, matches exact words and
phrases in documents. It uses algorithms like BM25 (Best Match 25) to rank documents based
on term frequency, inverse document frequency, and document length normalization.

BM25 is particularly effective for queries with specific terminology, product codes, names,
and acronyms. It excels when the exact terms matter, such as searching for "COVID-19" versus
"coronavirus pandemic" - these might be semantically similar but lexically distinct.

Full-text search engines like PostgreSQL FTS, Elasticsearch, and Solr implement BM25-like
ranking algorithms. They create inverted indexes mapping terms to documents for fast lookup.
""",
            "Keyword Search Overview",
        ),
        (
            "rag_systems.txt",
            b"""Retrieval-Augmented Generation Systems

RAG (Retrieval-Augmented Generation) combines information retrieval with large language
models to generate accurate, grounded responses. The system retrieves relevant documents
using semantic search, then provides them as context to the LLM for generation.

This approach addresses LLM hallucination by grounding responses in retrieved facts.
The retrieval component acts as the model's "memory", pulling in relevant information
from a knowledge base. The generation component then synthesizes this information into
coherent, contextual responses with proper citations.

Key components of RAG systems include: document chunking, embedding generation, vector
database storage (like Qdrant or Pinecone), retrieval algorithms, and LLM integration
with providers like OpenAI, Anthropic, or Google Gemini.
""",
            "RAG Systems Explained",
        ),
        (
            "hybrid_fusion.txt",
            b"""Hybrid Search and Reciprocal Rank Fusion

Hybrid search combines semantic vector search with keyword search to achieve better
accuracy than either method alone. Research shows 18-22% improvement over single-method
approaches by balancing semantic understanding with exact term matching.

Reciprocal Rank Fusion (RRF) is a rank-based fusion algorithm that combines multiple
ranked lists without requiring score normalization. The formula is:
score(document) = sum(1 / (k + rank_i(document))) across all rankings i,
where k=60 is the research-proven optimal constant.

RRF is particularly effective because it doesn't require normalizing different scoring
systems (cosine similarity vs BM25) and is robust to outliers. It naturally gives higher
scores to documents appearing in multiple result sets with good ranks.
""",
            "Hybrid Search with RRF",
        ),
        (
            "cross_encoder.txt",
            b"""Cross-Encoder Reranking for Precision

Two-stage retrieval uses fast bi-encoders for candidate generation followed by accurate
cross-encoders for reranking. This approach optimizes both recall (first stage) and
precision (second stage) in the retrieval pipeline.

Bi-encoders (like sentence-transformers) embed queries and documents independently,
enabling fast vector similarity search. However, they don't model query-document
interactions directly. Cross-encoders process query and document together through BERT,
allowing attention between all tokens for more accurate relevance scoring.

Cross-encoder reranking provides 8-12% improvement in precision@10 over bi-encoder
similarity alone. The MS MARCO MiniLM cross-encoder is trained on millions of
query-passage pairs from Bing search logs, making it highly effective for passage ranking.

The computational cost is mitigated by applying cross-encoders only to top-k candidates
(typically 50-100) rather than the entire corpus.
""",
            "Cross-Encoder Reranking",
        ),
    ]

    uploaded_docs = []

    try:
        # Upload each document
        for filename, content, title in documents:
            files = {"file": (filename, content, "text/plain")}
            data = {"title": title, "description": f"Integration test: {title}"}

            response = await api_client.post(
                "/api/v1/documents/upload", files=files, data=data
            )
            assert response.status_code == 201, (
                f"Failed to upload {filename}: {response.status_code} - {response.text}"
            )

            result = response.json()
            document = result["document"]
            uploaded_docs.append(
                {
                    "id": document["id"],
                    "title": title,
                    "filename": filename,
                    "content": content.decode("utf-8"),
                }
            )

        # Wait for all documents to be processed (embedding + Qdrant storage)
        max_wait_seconds = 60
        for doc_info in uploaded_docs:
            doc_id = doc_info["id"]
            for _ in range(max_wait_seconds):
                response = await api_client.get(f"/api/v1/documents/{doc_id}")
                assert response.status_code == 200

                document = response.json()
                if (
                    document["upload_status"] == "completed"
                    and document.get("embedding_status") == "completed"
                ):
                    break

                await asyncio.sleep(1)
            else:
                pytest.fail(
                    f"Document {doc_id} processing did not complete within {max_wait_seconds}s"
                )

        # Additional wait to ensure Qdrant indexing is complete
        await asyncio.sleep(2)

        yield uploaded_docs

    finally:
        # Cleanup: Delete all uploaded documents
        for doc_info in uploaded_docs:
            try:
                await api_client.delete(f"/api/v1/documents/{doc_info['id']}")
            except Exception as e:
                # Log but don't fail test on cleanup errors
                print(f"Warning: Failed to delete document {doc_info['id']}: {e}")


@pytest.mark.asyncio
async def test_vector_search_returns_results(
    api_client: httpx.AsyncClient, test_corpus: list[dict]
) -> None:
    """Test pure vector search returns semantically relevant results.

    Verifies that vector-only search mode:
    1. Returns results for semantic queries
    2. Results are ordered by relevance score (descending)
    3. Top results are semantically relevant to query
    4. Scores are in valid range [0, 1]

    Args:
        api_client: HTTP client for API service.
        test_corpus: Test documents with known content.
    """
    # Search for semantic concept (should match semantic_search.txt)
    response = await api_client.post(
        "/api/v1/search",
        json={"query": "neural language models for understanding text meaning", "top_k": 5},
        params={"mode": "vector", "use_reranking": "false"},
    )

    assert response.status_code == 200, (
        f"Vector search failed: {response.status_code} - {response.text}"
    )

    result = response.json()
    assert "results" in result, "Response missing 'results' field"
    assert "total_results" in result, "Response missing 'total_results' field"

    results = result["results"]
    assert len(results) > 0, "Vector search returned no results"

    # Verify result structure
    for idx, search_result in enumerate(results):
        assert "chunk_id" in search_result, f"Result {idx} missing 'chunk_id'"
        assert "document_id" in search_result, f"Result {idx} missing 'document_id'"
        assert "content" in search_result, f"Result {idx} missing 'content'"
        assert "score" in search_result, f"Result {idx} missing 'score'"
        assert "document_title" in search_result, f"Result {idx} missing 'document_title'"

        # Verify score is valid
        score = search_result["score"]
        assert 0.0 <= score <= 1.0, f"Invalid score {score} (must be in [0, 1])"
        assert len(search_result["content"]) > 0, f"Result {idx} has empty content"

    # Verify results are ordered by score (descending)
    scores = [r["score"] for r in results]
    assert scores == sorted(scores, reverse=True), (
        "Vector search results not sorted by score (descending)"
    )

    # Verify semantic relevance: top result should be from semantic_search.txt
    # Query was about "neural language models for understanding text meaning"
    top_result = results[0]
    top_content = top_result["content"].lower()
    assert (
        "semantic" in top_content
        or "embedding" in top_content
        or "vector" in top_content
        or "neural" in top_content
    ), f"Top result not semantically relevant: {top_content[:200]}"


@pytest.mark.asyncio
async def test_keyword_search_returns_results(
    api_client: httpx.AsyncClient, test_corpus: list[dict]
) -> None:
    """Test pure keyword search returns lexically matching results.

    Verifies that keyword-only search mode:
    1. Returns results for exact term matches
    2. Results contain the queried keywords
    3. Results are ranked by BM25 relevance
    4. Scores reflect term matching quality

    Args:
        api_client: HTTP client for API service.
        test_corpus: Test documents with known content.
    """
    # Search for specific terms (should match keyword_search.txt strongly)
    response = await api_client.post(
        "/api/v1/search",
        json={"query": "BM25 term frequency inverted index", "top_k": 5},
        params={"mode": "keyword", "use_reranking": "false"},
    )

    assert response.status_code == 200, (
        f"Keyword search failed: {response.status_code} - {response.text}"
    )

    result = response.json()
    results = result["results"]
    assert len(results) > 0, "Keyword search returned no results"

    # Verify results are scored
    for search_result in results:
        assert search_result["score"] > 0, "Keyword result has zero/negative score"

    # Verify results are ordered by score (descending)
    scores = [r["score"] for r in results]
    assert scores == sorted(scores, reverse=True), (
        "Keyword search results not sorted by score (descending)"
    )

    # Verify lexical relevance: at least one result should contain "BM25"
    bm25_found = any("bm25" in r["content"].lower() for r in results)
    assert bm25_found, "No results contain 'BM25' despite keyword search"


@pytest.mark.asyncio
async def test_hybrid_search_combines_vector_and_keyword(
    api_client: httpx.AsyncClient, test_corpus: list[dict]
) -> None:
    """Test hybrid search combines vector and keyword results using RRF fusion.

    Verifies that hybrid search mode:
    1. Returns results that benefit from both semantic and lexical matching
    2. Results are ordered by RRF fusion score (descending)
    3. Fusion combines strengths of both methods
    4. Scores are properly normalized

    This test uses a query that benefits from hybrid approach:
    - Semantic component: "finding relevant documents"
    - Lexical component: specific terms like "RRF", "fusion"

    Args:
        api_client: HTTP client for API service.
        test_corpus: Test documents with known content.
    """
    # Query that benefits from hybrid: semantic concept + specific terminology
    response = await api_client.post(
        "/api/v1/search",
        json={
            "query": "combining semantic search with keyword matching using RRF fusion",
            "top_k": 5,
        },
        params={"mode": "hybrid", "use_reranking": "false"},
    )

    assert response.status_code == 200, (
        f"Hybrid search failed: {response.status_code} - {response.text}"
    )

    result = response.json()
    results = result["results"]
    assert len(results) > 0, "Hybrid search returned no results"

    # Verify all results have valid scores
    for search_result in results:
        score = search_result["score"]
        assert score > 0, f"Hybrid result has zero/negative score: {score}"

    # Verify results are ordered by score (descending)
    scores = [r["score"] for r in results]
    assert scores == sorted(scores, reverse=True), (
        "Hybrid search results not sorted by score (descending)"
    )

    # Verify hybrid benefits: should find document about RRF/fusion
    # (benefits from both semantic understanding AND keyword match)
    fusion_found = any(
        "rrf" in r["content"].lower() or "fusion" in r["content"].lower()
        for r in results
    )
    assert fusion_found, "Hybrid search didn't find RRF/fusion document"

    # Top results should be highly relevant to both semantic and lexical aspects
    top_result = results[0]
    top_content = top_result["content"].lower()

    # Should have semantic concepts OR lexical matches
    has_semantic = any(
        term in top_content
        for term in ["semantic", "hybrid", "search", "retrieval"]
    )
    has_lexical = any(
        term in top_content for term in ["rrf", "fusion", "rank", "keyword"]
    )

    assert has_semantic or has_lexical, (
        f"Top hybrid result lacks both semantic and lexical relevance: {top_content[:200]}"
    )


@pytest.mark.asyncio
async def test_reranking_improves_precision(
    api_client: httpx.AsyncClient, test_corpus: list[dict]
) -> None:
    """Test that cross-encoder reranking improves result precision.

    Verifies that reranking:
    1. Changes the order of results compared to initial retrieval
    2. Assigns more accurate relevance scores
    3. Pushes more relevant results to the top
    4. Normalized scores are in [0, 1] range

    Compares hybrid search with and without reranking to verify
    that reranking improves result ordering.

    Args:
        api_client: HTTP client for API service.
        test_corpus: Test documents with known content.
    """
    query = "how do cross-encoders improve precision in retrieval systems"

    # Search WITHOUT reranking
    response_no_rerank = await api_client.post(
        "/api/v1/search",
        json={"query": query, "top_k": 10},
        params={"mode": "hybrid", "use_reranking": "false"},
    )
    assert response_no_rerank.status_code == 200
    results_no_rerank = response_no_rerank.json()["results"]

    # Search WITH reranking
    response_with_rerank = await api_client.post(
        "/api/v1/search",
        json={"query": query, "top_k": 10},
        params={"mode": "hybrid", "use_reranking": "true"},
    )
    assert response_with_rerank.status_code == 200
    results_with_rerank = response_with_rerank.json()["results"]

    # Both should return results
    assert len(results_no_rerank) > 0, "No results without reranking"
    assert len(results_with_rerank) > 0, "No results with reranking"

    # Verify reranking changed the ordering (extract chunk IDs)
    chunk_ids_no_rerank = [r["chunk_id"] for r in results_no_rerank]
    chunk_ids_with_rerank = [r["chunk_id"] for r in results_with_rerank]

    # Ordering should be different (reranking changes ranks)
    # Note: It's possible they're the same if results were already optimal,
    # but with diverse corpus, they should differ
    ordering_changed = chunk_ids_no_rerank != chunk_ids_with_rerank

    # Verify scores changed (reranking assigns new scores)
    scores_no_rerank = [r["score"] for r in results_no_rerank]
    scores_with_rerank = [r["score"] for r in results_with_rerank]

    # Scores should be different after reranking
    scores_changed = scores_no_rerank != scores_with_rerank

    # At least one of these should be true (ordering or scores changed)
    assert ordering_changed or scores_changed, (
        "Reranking had no effect on results (neither ordering nor scores changed)"
    )

    # Verify reranked scores are normalized [0, 1]
    for result in results_with_rerank:
        score = result["score"]
        assert 0.0 <= score <= 1.0, f"Reranked score {score} not in [0, 1]"

    # Verify reranked results are ordered by score (descending)
    assert scores_with_rerank == sorted(scores_with_rerank, reverse=True), (
        "Reranked results not sorted by score (descending)"
    )

    # Verify reranking improved relevance: top result with reranking should be
    # about cross-encoders or precision/reranking
    top_reranked = results_with_rerank[0]
    top_content = top_reranked["content"].lower()

    # Should be about cross-encoders, reranking, or precision
    relevant_terms = ["cross-encoder", "rerank", "precision", "two-stage", "bi-encoder"]
    has_relevant_term = any(term in top_content for term in relevant_terms)

    assert has_relevant_term, (
        f"Reranked top result not about cross-encoders/reranking: {top_content[:200]}"
    )


@pytest.mark.asyncio
async def test_full_search_workflow_end_to_end(
    api_client: httpx.AsyncClient, test_corpus: list[dict]
) -> None:
    """Test complete search workflow: API → Search → Embedder → Qdrant → Reranking.

    This is the comprehensive end-to-end test verifying:
    1. Search query is accepted by API
    2. Query is embedded via embedder microservice
    3. Vector search executes against Qdrant
    4. Keyword search executes against PostgreSQL
    5. Results are fused using RRF
    6. Cross-encoder reranking improves precision
    7. Results are ordered by relevance score (descending)
    8. Response format is correct

    This test exercises the complete production search pipeline with all
    optimizations enabled (hybrid mode + reranking).

    Args:
        api_client: HTTP client for API service.
        test_corpus: Test documents with known content.
    """
    # Execute full search with all features enabled
    query = "retrieval augmented generation with semantic search and citations"

    response = await api_client.post(
        "/api/v1/search",
        json={"query": query, "top_k": 10},
        params={
            "mode": "hybrid",  # RRF fusion of vector + keyword
            "use_reranking": "true",  # Cross-encoder precision improvement
            "use_expansion": "false",  # Disable expansion for deterministic test
        },
    )

    # Verify request succeeded
    assert response.status_code == 200, (
        f"Search request failed: {response.status_code} - {response.text}"
    )

    result = response.json()

    # Verify response structure
    assert "query" in result, "Response missing 'query' field"
    assert "results" in result, "Response missing 'results' field"
    assert "total_results" in result, "Response missing 'total_results' field"

    # Verify query echo
    assert result["query"] == query, "Query echo mismatch"

    # Verify results returned
    results = result["results"]
    assert len(results) > 0, "Search returned no results"
    assert result["total_results"] == len(results), "total_results count mismatch"

    # Verify each result has complete structure
    for idx, search_result in enumerate(results):
        # Required fields
        assert "chunk_id" in search_result, f"Result {idx} missing chunk_id"
        assert "document_id" in search_result, f"Result {idx} missing document_id"
        assert "content" in search_result, f"Result {idx} missing content"
        assert "score" in search_result, f"Result {idx} missing score"
        assert "document_title" in search_result, f"Result {idx} missing document_title"
        assert "document_file_name" in search_result, (
            f"Result {idx} missing document_file_name"
        )

        # Verify score validity (reranking produces [0, 1])
        score = search_result["score"]
        assert 0.0 <= score <= 1.0, (
            f"Result {idx} has invalid score {score} (expected [0, 1])"
        )
        assert score > 0, f"Result {idx} has zero score"

        # Verify content not empty
        assert len(search_result["content"]) > 0, f"Result {idx} has empty content"

        # Verify document_id matches one of our test corpus documents
        doc_id = search_result["document_id"]
        corpus_ids = [doc["id"] for doc in test_corpus]
        assert doc_id in corpus_ids, (
            f"Result {idx} document_id {doc_id} not in test corpus"
        )

    # Verify results are ordered by score (descending)
    scores = [r["score"] for r in results]
    assert scores == sorted(scores, reverse=True), (
        "Results not sorted by relevance score (descending)"
    )

    # Verify score distribution (top results should have higher scores)
    if len(results) >= 3:
        top_score = scores[0]
        third_score = scores[2]
        assert top_score > third_score, (
            "Top result should have higher score than 3rd result"
        )

    # Verify semantic relevance of top result
    # Query was about "retrieval augmented generation with semantic search"
    top_result = results[0]
    top_content = top_result["content"].lower()

    # Should contain terms related to RAG, retrieval, or semantic search
    relevant_terms = [
        "rag",
        "retrieval",
        "augmented",
        "generation",
        "semantic",
        "search",
        "embedding",
        "vector",
    ]
    matches = sum(1 for term in relevant_terms if term in top_content)

    assert matches >= 2, (
        f"Top result lacks semantic relevance (only {matches}/8 terms matched): "
        f"{top_content[:200]}"
    )

    # Verify no duplicate chunks in results (each chunk_id should be unique)
    chunk_ids = [r["chunk_id"] for r in results]
    assert len(chunk_ids) == len(set(chunk_ids)), (
        "Search results contain duplicate chunks"
    )


@pytest.mark.asyncio
async def test_search_with_empty_query_fails(api_client: httpx.AsyncClient) -> None:
    """Test that empty query returns proper error response.

    Verifies that the search API properly validates queries and returns
    400 Bad Request for empty or whitespace-only queries.

    Args:
        api_client: HTTP client for API service.
    """
    # Test empty string
    response = await api_client.post(
        "/api/v1/search",
        json={"query": "", "top_k": 10},
    )
    assert response.status_code == 400, (
        f"Expected 400 for empty query, got {response.status_code}"
    )

    # Test whitespace-only
    response = await api_client.post(
        "/api/v1/search",
        json={"query": "   ", "top_k": 10},
    )
    assert response.status_code == 400, (
        f"Expected 400 for whitespace query, got {response.status_code}"
    )


@pytest.mark.asyncio
async def test_search_result_ordering_by_score(
    api_client: httpx.AsyncClient, test_corpus: list[dict]
) -> None:
    """Test that all search modes return results ordered by score (descending).

    Verifies that result ordering by relevance score is consistent across
    all search modes: vector, keyword, and hybrid.

    Args:
        api_client: HTTP client for API service.
        test_corpus: Test documents with known content.
    """
    query = "document retrieval and ranking algorithms"

    # Test each search mode
    for mode in ["vector", "keyword", "hybrid"]:
        response = await api_client.post(
            "/api/v1/search",
            json={"query": query, "top_k": 10},
            params={"mode": mode, "use_reranking": "false"},
        )

        assert response.status_code == 200, (
            f"{mode} search failed: {response.status_code}"
        )

        results = response.json()["results"]
        if len(results) > 0:
            scores = [r["score"] for r in results]
            assert scores == sorted(scores, reverse=True), (
                f"{mode} mode results not sorted by score (descending): {scores}"
            )

            # Verify all scores are positive
            assert all(s > 0 for s in scores), (
                f"{mode} mode has non-positive scores: {scores}"
            )
