apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: raas

bases:
- ../../base

patchesStrategicMerge:
- replica-patches.yaml
- resource-patches.yaml
- storage-patches.yaml

# Use local images
images:
- name: raas-api
  newTag: latest
- name: raas-embedder
  newTag: latest
- name: raas-frontend
  newTag: latest
- name: raas-generator
  newTag: latest
