apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedder-model-cache
  namespace: raas
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
