apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: raas
type: Opaque
stringData:
  POSTGRES_DB: raasdb
  POSTGRES_USER: raasuser
  POSTGRES_PASSWORD: raaspass
  DATABASE_URL: postgresql+asyncpg://raasuser:raaspass@postgres:5432/raasdb
