apiVersion: v1
kind: ConfigMap
metadata:
  name: generator-config
  namespace: raas
data:
  OLLAMA_URL: "http://ollama:11434"
  DEFAULT_MODEL: "llama3.2"
  MAX_CHUNKS: "5"
  TEMPERATURE: "0.1"
  MAX_TOKENS: "2000"
  TIMEOUT: "30"
