import pytest
from app.providers.registry import ProviderRegistry
from app.providers.base import ModelProvider
from app.models.schemas import Model


class MockProvider(ModelProvider):
    """Mock provider for testing."""

    def __init__(self, name: str, models: list, available: bool = True):
        self._name = name
        self._models = models
        self._available = available

    async def list_models(self):
        return self._models

    async def generate(self, model: str, prompt: str, context: str) -> str:
        return f"Generated by {self._name}"

    def is_available(self) -> bool:
        return self._available


@pytest.mark.asyncio
async def test_registry_initialization():
    """Registry starts empty"""
    registry = ProviderRegistry()
    assert len(registry.providers) == 0


@pytest.mark.asyncio
async def test_register_available_provider():
    """Register provider that is available"""
    registry = ProviderRegistry()
    provider = MockProvider("test", [], available=True)

    registry.register("test", provider)

    assert "test" in registry.providers
    assert registry.providers["test"] == provider


@pytest.mark.asyncio
async def test_skip_unavailable_provider():
    """Do not register provider that is unavailable"""
    registry = ProviderRegistry()
    provider = MockProvider("test", [], available=False)

    registry.register("test", provider)

    assert "test" not in registry.providers


@pytest.mark.asyncio
async def test_list_all_models_aggregates():
    """list_all_models aggregates from all providers"""
    model1 = Model(
        name="test1:model1",
        display_name="Model 1",
        provider="test1",
        size="8B",
        description="Test model 1",
        modified_at="2025-10-24T10:00:00Z"
    )
    model2 = Model(
        name="test2:model2",
        display_name="Model 2",
        provider="test2",
        size="70B",
        description="Test model 2",
        modified_at="2025-10-24T10:00:00Z"
    )

    registry = ProviderRegistry()
    registry.register("test1", MockProvider("test1", [model1]))
    registry.register("test2", MockProvider("test2", [model2]))

    models = await registry.list_all_models()

    assert len(models) == 2
    assert model1 in models
    assert model2 in models


@pytest.mark.asyncio
async def test_generate_routes_to_provider():
    """generate routes to correct provider based on model name"""
    registry = ProviderRegistry()
    registry.register("test", MockProvider("test", []))

    summary, provider_name = await registry.generate("test:model", "prompt", "context")

    assert summary == "Generated by test"
    assert provider_name == "test"


@pytest.mark.asyncio
async def test_generate_raises_on_unknown_provider():
    """generate raises ValueError for unknown provider"""
    registry = ProviderRegistry()

    with pytest.raises(ValueError, match="Cannot determine provider"):
        await registry.generate("unknown:model", "prompt", "context")


def test_model_aliases_contains_all_new_models():
    """Test that MODEL_ALIASES includes all new friendly model names."""
    from app.providers.registry import ProviderRegistry

    expected_aliases = {
        "gpt-5": ("openai", "gpt-5"),
        "gpt-5-mini": ("openai", "gpt-5-mini"),
        "sonnet-4.5": ("anthropic", "claude-sonnet-4-5-20250929"),
        "opus-4.1": ("anthropic", "claude-opus-4-1-20250805"),
        "haiku-4.5": ("anthropic", "claude-haiku-4-5-20251001"),
        "gemini-flash-2.5": ("google", "gemini-2.5-flash"),
        "gemini-pro-2.5": ("google", "gemini-2.5-pro"),
    }

    assert hasattr(ProviderRegistry, 'MODEL_ALIASES')
    assert ProviderRegistry.MODEL_ALIASES == expected_aliases


def test_extract_provider_from_standalone_alias():
    """Test that standalone aliases map to correct provider."""
    registry = ProviderRegistry()

    # Test each alias
    assert registry._extract_provider("gpt-5") == "openai"
    assert registry._extract_provider("gpt-5-mini") == "openai"
    assert registry._extract_provider("sonnet-4.5") == "anthropic"
    assert registry._extract_provider("opus-4.1") == "anthropic"
    assert registry._extract_provider("haiku-4.5") == "anthropic"
    assert registry._extract_provider("gemini-flash-2.5") == "google"
    assert registry._extract_provider("gemini-pro-2.5") == "google"


def test_extract_provider_from_prefixed_format():
    """Test that provider:model format still works."""
    registry = ProviderRegistry()

    assert registry._extract_provider("openai:gpt-4o") == "openai"
    assert registry._extract_provider("anthropic:claude-3") == "anthropic"
    assert registry._extract_provider("google:gemini-1.5") == "google"


def test_extract_provider_raises_on_unknown_model():
    """Test that unknown model raises ValueError."""
    registry = ProviderRegistry()

    with pytest.raises(ValueError) as exc_info:
        registry._extract_provider("unknown-model")

    assert "Cannot determine provider" in str(exc_info.value)
    assert "unknown-model" in str(exc_info.value)
    assert "supported aliases" in str(exc_info.value)
