import React from 'react';

interface SummaryDisplayProps {
  summary: string;
  modelUsed: string;
}

export const SummaryDisplay: React.FC<SummaryDisplayProps> = ({
  summary,
  modelUsed
}) => {
  // Parse citations and create clickable links
  const renderSummaryWithCitations = () => {
    // Match [1], [2], etc.
    const citationPattern = /\[(\d+)\]/g;
    const parts: React.ReactNode[] = [];
    let lastIndex = 0;
    let match: RegExpExecArray | null;

    while ((match = citationPattern.exec(summary)) !== null) {
      // Add text before citation
      if (match.index > lastIndex) {
        parts.push(summary.substring(lastIndex, match.index));
      }

      // Add citation
      const citationNum = parseInt(match[1]);
      parts.push(
        <span
          key={`citation-${match.index}`}
          className="inline-flex items-center px-1.5 py-0.5 mx-0.5 text-xs font-medium text-blue-700 bg-blue-100 rounded"
          aria-label={`Source ${citationNum}`}
        >
          {match[0]}
        </span>
      );

      lastIndex = match.index + match[0].length;
    }

    // Add remaining text
    if (lastIndex < summary.length) {
      parts.push(summary.substring(lastIndex));
    }

    return parts;
  };

  return (
    <div className="bg-white rounded-lg shadow-md p-6 mb-6">
      <div className="prose max-w-none">
        <p className="text-lg leading-relaxed text-gray-900">
          {renderSummaryWithCitations()}
        </p>
      </div>
      <div className="mt-4 pt-4 border-t border-gray-200">
        <p className="text-sm text-gray-500">
          Generated by <span className="font-medium">{modelUsed}</span>
        </p>
      </div>
    </div>
  );
};
